train:
  learning_rate: 5e-5
  batch_size: 16
  num_epochs: 3
  weight_decay: 0.01
  warmup_ratio: 0.1
  gradient_accumulation_steps: 4

  save_total_limit: 3
  load_best_model_at_end: false
  metric_for_best_model: "f1"
  greater_is_better: true
